/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun Feb  4 15:05:56 2018"
#define BUILD_TIME (1517785556UL)

#define VERSION_NUMBER 0x03060100UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0xf88195c4UL
#define VERSION_SANITY3 0x00025000UL

#define VERSION_STRING "3.6.1-0"
#define VERSION_ID \
 "Windows NetHack Beta Version 3.6.1-0 - last build Sun Feb  4 15:05:56 2018."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.1-0 Windows Beta, built Feb  4 15:05:56 2018."

